# Generated by Django 5.0.6 on 2024-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityPointsApp', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='activity_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
