# Generated by Django 5.0.6 on 2024-07-10 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityPointsApp', '0003_alter_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(default='Social Work', on_delete=django.db.models.deletion.CASCADE, to='activityPointsApp.activitycategory'),
        ),
    ]
